/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Dimensión N (https://sketchfab.com/dimensionn)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/aba9c319497c4c5f8c62cd109b3e9242
title: 3d Poop Emoji
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
import { BASE_URL } from 'src/constants/app'
import { useFrame } from '@react-three/fiber'

const MODEL_FILE = `${BASE_URL}/assets/3d/models/game/poop-emoji.glb`

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.Mesh
    mesh_1: THREE.Mesh
    mesh_2: THREE.Mesh
    mesh_3: THREE.Mesh
    mesh_4: THREE.Mesh
    mesh_5: THREE.Mesh
  }
  materials: {
    Blanco_Ojos: THREE.MeshStandardMaterial
    Cafe: THREE.MeshStandardMaterial
    Custom: THREE.MeshStandardMaterial
    Default: THREE.MeshStandardMaterial
  }
}

export function PoopEmoji(props: JSX.IntrinsicElements['group']) {
  const groupRef = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF(MODEL_FILE) as GLTFResult

  const { scale = [0.025, 0.025, 0.025], ...restProps } = props

  useFrame(() => {
    if (!groupRef.current) {
      return
    }

    groupRef.current.rotation.y += 0.02
  })

  return (
    <group ref={groupRef} scale={scale} {...restProps} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, Math.PI / 12]}>
        <group
        // position={[-149.41, 912.18, 171.25]}
        >
          <mesh geometry={nodes.mesh_0.geometry} material={materials.Blanco_Ojos} />
          <mesh geometry={nodes.mesh_1.geometry} material={nodes.mesh_1.material} />
          <mesh geometry={nodes.mesh_2.geometry} material={nodes.mesh_2.material} />
          <mesh geometry={nodes.mesh_3.geometry} material={materials.Custom} />
          <mesh geometry={nodes.mesh_4.geometry} material={nodes.mesh_4.material} />
          <mesh geometry={nodes.mesh_5.geometry} material={nodes.mesh_5.material} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(MODEL_FILE)

export default PoopEmoji
