import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
import { BASE_URL } from 'src/constants/app'

const MODEL_FILE = `${BASE_URL}/assets/3d/scenes/cloud-sphere-orange.glb`

/*
original tsx generated by: https://github.com/pmndrs/gltfjsx
tsx modified by: @firxworx

model author: Oscar R (https://sketchfab.com/braidoner)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/star-wars-low-poly-tatooine-skybox-4acf1cbebe674e128b4bf68e9897ae3e
title: Star Wars - Low Poly Tatooine Skybox
*/

type GLTFResult = GLTF & {
  nodes: {
    cloud19_lambert1_0: THREE.Mesh
    cloud20_lambert1_0: THREE.Mesh
    polySurface32_lambert1_0: THREE.Mesh
    polySurface21_lambert1_0: THREE.Mesh
    polySurface17_lambert1_0: THREE.Mesh
    polySurface16_lambert1_0: THREE.Mesh
    polySurface18_lambert1_0: THREE.Mesh
    polySurface15_lambert1_0: THREE.Mesh
    polySurface23_lambert1_0: THREE.Mesh
    polySurface22_lambert1_0: THREE.Mesh
    polySurface20_lambert1_0: THREE.Mesh
    polySurface19_lambert1_0: THREE.Mesh
    polySurface12_lambert1_0: THREE.Mesh
    polySurface14_lambert1_0: THREE.Mesh
    polySurface13_lambert1_0: THREE.Mesh
    polySurface8_lambert1_0: THREE.Mesh
    polySurface10_lambert1_0: THREE.Mesh
    polySurface11_lambert1_0: THREE.Mesh
    polySurface6_lambert1_0: THREE.Mesh
    polySurface7_lambert1_0: THREE.Mesh
    polySurface9_lambert1_0: THREE.Mesh
    polySurface41_lambert1_0: THREE.Mesh
    polySurface42_lambert1_0: THREE.Mesh
    polySurface40_lambert1_0: THREE.Mesh
    polySurface39_lambert1_0: THREE.Mesh
    polySurface38_lambert1_0: THREE.Mesh
    polySurface37_lambert1_0: THREE.Mesh
    polySurface36_lambert1_0: THREE.Mesh
    polySurface35_lambert1_0: THREE.Mesh
    polySurface34_lambert1_0: THREE.Mesh
    polySurface33_lambert1_0: THREE.Mesh
    polySurface31_lambert1_0: THREE.Mesh
    polySurface30_lambert1_0: THREE.Mesh
    polySurface29_lambert1_0: THREE.Mesh
    polySurface28_lambert1_0: THREE.Mesh
    polySurface27_lambert1_0: THREE.Mesh
    polySurface26_lambert1_0: THREE.Mesh
    polySurface25_lambert1_0: THREE.Mesh
    polySurface24_lambert1_0: THREE.Mesh
    tatooine_sky_lambert1_0: THREE.Mesh
  }
  materials: {
    lambert1: THREE.MeshStandardMaterial
  }
}

export function CloudSphereOrange(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF(MODEL_FILE) as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[148.51, -273.4, 146.34]} rotation={[-3.13, 0.73, -3.07]} scale={[4.08, 4.08, 4.08]}>
            <mesh geometry={nodes.cloud19_lambert1_0.geometry} material={nodes.cloud19_lambert1_0.material} />
          </group>
          <group position={[-190.48, 246.52, 48.08]} rotation={[-3.14, -0.2, -0.02]} scale={[4.08, 4.08, 4.08]}>
            <mesh geometry={nodes.cloud20_lambert1_0.geometry} material={nodes.cloud20_lambert1_0.material} />
          </group>
          <group rotation={[-Math.PI, 0.74, -Math.PI]}>
            <group position={[0, -4.39, 0]} rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.polySurface32_lambert1_0.geometry}
                material={nodes.polySurface32_lambert1_0.material}
              />
            </group>
            <group rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.polySurface21_lambert1_0.geometry}
                material={nodes.polySurface21_lambert1_0.material}
              />
            </group>
            <group position={[0, 18.42, -25.15]} rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.polySurface17_lambert1_0.geometry}
                material={nodes.polySurface17_lambert1_0.material}
              />
            </group>
            <group rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.polySurface16_lambert1_0.geometry}
                material={nodes.polySurface16_lambert1_0.material}
              />
            </group>
            <group rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.polySurface18_lambert1_0.geometry}
                material={nodes.polySurface18_lambert1_0.material}
              />
            </group>
            <group rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.polySurface15_lambert1_0.geometry}
                material={nodes.polySurface15_lambert1_0.material}
              />
            </group>
            <group rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.polySurface23_lambert1_0.geometry}
                material={nodes.polySurface23_lambert1_0.material}
              />
            </group>
            <group rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.polySurface22_lambert1_0.geometry}
                material={nodes.polySurface22_lambert1_0.material}
              />
            </group>
            <group rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.polySurface20_lambert1_0.geometry}
                material={nodes.polySurface20_lambert1_0.material}
              />
            </group>
            <group rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.polySurface19_lambert1_0.geometry}
                material={nodes.polySurface19_lambert1_0.material}
              />
            </group>
            <group rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.polySurface12_lambert1_0.geometry}
                material={nodes.polySurface12_lambert1_0.material}
              />
            </group>
            <group rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.polySurface14_lambert1_0.geometry}
                material={nodes.polySurface14_lambert1_0.material}
              />
            </group>
            <group rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.polySurface13_lambert1_0.geometry}
                material={nodes.polySurface13_lambert1_0.material}
              />
            </group>
            <group rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.polySurface8_lambert1_0.geometry}
                material={nodes.polySurface8_lambert1_0.material}
              />
            </group>
            <group rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.polySurface10_lambert1_0.geometry}
                material={nodes.polySurface10_lambert1_0.material}
              />
            </group>
            <group rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.polySurface11_lambert1_0.geometry}
                material={nodes.polySurface11_lambert1_0.material}
              />
            </group>
            <group rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.polySurface6_lambert1_0.geometry}
                material={nodes.polySurface6_lambert1_0.material}
              />
            </group>
            <group rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.polySurface7_lambert1_0.geometry}
                material={nodes.polySurface7_lambert1_0.material}
              />
            </group>
            <group rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.polySurface9_lambert1_0.geometry}
                material={nodes.polySurface9_lambert1_0.material}
              />
            </group>
            <group position={[33.28, -48.73, 2.22]} rotation={[0, 0.54, 0]}>
              <mesh
                geometry={nodes.polySurface41_lambert1_0.geometry}
                material={nodes.polySurface41_lambert1_0.material}
              />
            </group>
            <group position={[30.86, -66.32, 0.34]} rotation={[0, 0.54, 0]}>
              <mesh
                geometry={nodes.polySurface42_lambert1_0.geometry}
                material={nodes.polySurface42_lambert1_0.material}
              />
            </group>
          </group>
          <group rotation={[0, 0.72, 0]}>
            <group position={[0, -51.34, 0]} rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.polySurface40_lambert1_0.geometry}
                material={nodes.polySurface40_lambert1_0.material}
              />
            </group>
            <group position={[-273.92, 0, -315.95]} rotation={[-Math.PI, -0.01, -Math.PI]}>
              <mesh
                geometry={nodes.polySurface39_lambert1_0.geometry}
                material={nodes.polySurface39_lambert1_0.material}
              />
            </group>
            <group position={[0, -20.37, 0]} rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.polySurface38_lambert1_0.geometry}
                material={nodes.polySurface38_lambert1_0.material}
              />
            </group>
            <group position={[0, -9.9, 0]} rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.polySurface37_lambert1_0.geometry}
                material={nodes.polySurface37_lambert1_0.material}
              />
            </group>
            <group position={[0, -12.28, 0]} rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.polySurface36_lambert1_0.geometry}
                material={nodes.polySurface36_lambert1_0.material}
              />
            </group>
            <group rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.polySurface35_lambert1_0.geometry}
                material={nodes.polySurface35_lambert1_0.material}
              />
            </group>
            <group position={[0, -46.23, 0]} rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.polySurface34_lambert1_0.geometry}
                material={nodes.polySurface34_lambert1_0.material}
              />
            </group>
            <group position={[0, -35.95, 0]} rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.polySurface33_lambert1_0.geometry}
                material={nodes.polySurface33_lambert1_0.material}
              />
            </group>
            <group position={[0, -45.71, 0]} rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.polySurface31_lambert1_0.geometry}
                material={nodes.polySurface31_lambert1_0.material}
              />
            </group>
            <group position={[0, -11.52, 0]} rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.polySurface30_lambert1_0.geometry}
                material={nodes.polySurface30_lambert1_0.material}
              />
            </group>
            <group rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.polySurface29_lambert1_0.geometry}
                material={nodes.polySurface29_lambert1_0.material}
              />
            </group>
            <group position={[0, -24.01, 0]} rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.polySurface28_lambert1_0.geometry}
                material={nodes.polySurface28_lambert1_0.material}
              />
            </group>
            <group position={[0, -33.29, -105.89]} rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.polySurface27_lambert1_0.geometry}
                material={nodes.polySurface27_lambert1_0.material}
              />
            </group>
            <group position={[0, -15.15, 0]} rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.polySurface26_lambert1_0.geometry}
                material={nodes.polySurface26_lambert1_0.material}
              />
            </group>
            <group rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.polySurface25_lambert1_0.geometry}
                material={nodes.polySurface25_lambert1_0.material}
              />
            </group>
            <group position={[0, -26.54, 0]} rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes.polySurface24_lambert1_0.geometry}
                material={nodes.polySurface24_lambert1_0.material}
              />
            </group>
          </group>
          <group position={[0, -0.28, 0]} scale={[269.62, 269.62, 269.62]}>
            <mesh geometry={nodes.tatooine_sky_lambert1_0.geometry} material={nodes.tatooine_sky_lambert1_0.material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(MODEL_FILE)
