/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Batuhan13 (https://sketchfab.com/Batuhan13)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/bob-lazar-ufo-75f488cec00e4dc88b7d6bc5867cdaef
title: Bob Lazar Ufo
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useMatcapTexture } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
import { BASE_URL } from 'src/constants/app'

const MODEL_FILE = `${BASE_URL}/assets/3d/models/vehicles/metal-ufo.glb`

type GLTFResult = GLTF & {
  nodes: {
    defaultMaterial: THREE.Mesh
  }
  materials: {
    material: THREE.MeshStandardMaterial
  }
}

export function MetalUFO(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF(MODEL_FILE) as GLTFResult

  // chrome 3B3C3F_DAD9D5_929290_ABACA8, bronze-ish gold 422509_C89536_824512_0A0604
  // bluey soft metal - 636D6C_D4E7ED_ABBCC4_9BA4A8
  // spacey gray - 64686F_BDC0C4_161718_A4A7AB
  // alien rainbow metal - 4F4C45_A7AEAA_7A8575_9D97A2
  // bronze 6E5137_E8CA90_271912_B99C74
  // subdued gold 71623B_ECDE8C_30250A_ABA69A
  // green shine gold 8B892C_D4E856_475E2D_47360A
  // PERFECT steel 686B73_2A2B2D_D5D9DD_B0B3BC
  // nice gold E6BF3C_5A4719_977726_FCFC82
  const [matcapMetal] = useMatcapTexture('686B73_2A2B2D_D5D9DD_B0B3BC', 1024)

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.material}>
            <meshMatcapMaterial attach="material" matcap={matcapMetal} />
          </mesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(MODEL_FILE)
