/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: quander (https://sketchfab.com/quander)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/animated-dog-shiba-inu-9abfce885a834399b2c3ccaed51cd474
title: Animated Dog, Shiba Inu
*/

import * as THREE from 'three'
import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
import { BASE_URL } from 'src/constants/app'
import { Position3D } from '../../../types/3d/position'

const MODEL_FILE = `${BASE_URL}/assets/3d/models/animals/puppy.glb`

type GLTFResult = GLTF & {
  nodes: {
    shiba_inu2_Material_0_0: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
  }
  materials: {
    Material_0: THREE.MeshStandardMaterial
  }
}

type ActionName = '0|play_dead_0' | '0|rollover_0' | '0|shake_0' | '0|sitting_0' | '0|standing_0'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

type ModelProps = JSX.IntrinsicElements['group'] & {
  position?: Position3D
}

export const Puppy: React.FC<ModelProps> = (props) => {
  const groupRef = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF(MODEL_FILE) as GLTFResult
  const { actions } = useAnimations<GLTFActions>(animations, groupRef)

  useEffect(() => {
    actions['0|sitting_0'].play()
  }, [actions])

  return (
    <group ref={groupRef} position={props.position ?? [0, 0, 0]} scale={[0.01, 0.01, 0.01]} dispose={null} {...props}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[0, 0, 0]}>
            <group name="0">
              <primitive object={nodes._rootJoint} />
              <skinnedMesh
                geometry={nodes.shiba_inu2_Material_0_0.geometry}
                material={materials.Material_0}
                skeleton={nodes.shiba_inu2_Material_0_0.skeleton}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(MODEL_FILE)

export default Puppy
